### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by kkxLly** [ankit16-py/YOLOv3-KCF-Fast-Object-Tracker#1]
Good work! dude. i have a idea wth yours about kcf_yolo. but i used yolov2, **fps is so low!!!**, what some tricks to improve it?

**Comment by ankitVP77** [comment]
Thank You for your kind words. If you are still getting low fps even with yolov2, one way to significantly boost fps is using GPU for inference. So basically if you have a powerful nvidia graphics card like gtx 1080/1070/1060/titan use can build opencv with dnn cuda support. So now the dnn module will run much faster and give better fps. 

First set up opencv with gpu support using this: https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/

then try it out using this: https://www.pyimagesearch.com/2020/02/10/opencv-dnn-with-nvidia-gpus-1549-faster-yolo-ssd-and-mask-r-cnn/

I don't have powerful GPUs so I never tried this out. Do tell me if it works.
